### ISSUE TITLE
Working

### ISSUE THREAD

**Issue by SinlesFlyer376** [RTGNetworkkk/ToDo#1]
Is ths working? havent tested yet but i dont want to download it till i know it is working.

**Comment by InspectorGadget** [comment]
Yes, this is working

**Comment by SinlesFlyer376** [comment]
Could I use my custom enchants plugin for this?

**Comment by SinlesFlyer376** [comment]
If you have an email I can send you the custom enchantment plugin

**Comment by SinlesFlyer376** [comment]
So you can edit it and put it on github or something like that

**Comment by SinlesFlyer376** [comment]
You could probably add more kits with the enchants on the custom enchants plugin

**Comment by SinlesFlyer376** [comment]
Or add to the config to what enchants to use in each kit

**Comment by InspectorGadget** [comment]
igadget28@gmail.com

**Comment by InspectorGadget** [comment]
Ok, sounds good
